const svg=(label:string,color:string,shape:string)=>`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420"><rect width="640" height="420" fill="#eaf1fa"/><rect x="65" y="85" width="510" height="260" rx="10" fill="${color}"/>${shape}<text x="320" y="388" text-anchor="middle" font-family="Arial" font-size="27" fill="#071b49">${label}</text></svg>`;
export const STARTER_FILES:Record<string,Record<string,string>>={
  'faq-finder':{
    'sample-faq.csv':'id,question,answer\n1,Where do I find the sample project?,Use the downloaded starter outline.\n2,Is this an official workshop syllabus?,No. The project cards are assessment examples.\n3,When is the workshop?,The date and time require organiser confirmation.\n4,Do I need a real email?,No. This demo accepts fictional example.com addresses only.\n5,What do I take home?,A small starter file and continuation checklist.\n',
    'test-questions.txt':'When is the workshop?\nIs this the official curriculum?\nWhere is the project starter?\n'
  },
  'sensor-explorer':{'sample-sensor.csv':'minute,temperature_c,light_lux\n0,24.1,310\n1,24.2,315\n2,24.0,309\n3,24.3,312\n4,29.1,310\n5,24.2,308\n6,24.1,900\n7,24.0,314\n','baseline-notes.txt':'Synthetic sample only. Plot temperature and light separately. Flag values outside a simple baseline such as 22-27 C or 200-600 lux. These thresholds are teaching examples, not equipment limits.\n'},
  'maintenance-notes':{'sample-maintenance.csv':'id,note\n1,Inspecting a loose belt on sample machine A\n2,Sample machine B made a new vibration sound\n3,Completed routine lubrication on sample machine A\n4,Rechecked belt tension on sample machine B\n5,Recorded a new vibration note after startup\n6,Completed general visual inspection\n','tag-rules.txt':'Try belt, vibration, lubrication and inspection as transparent keyword themes. Record unmatched notes. Do not infer machine condition from these fictional lines.\n'},
  'inspection-notes':{'sample-inspection.csv':'id,note\n1,Synthetic note: surface mark near column label A\n2,Synthetic note: paint wear on sample wall B\n3,Synthetic note: standing water in example corridor\n4,Synthetic note: revisit label on drawing C\n5,Synthetic note: photo reference missing\n6,Synthetic note: surface mark on example wall D\n','category-guide.txt':'Possible review categories: surface, water, documentation, other. This teaching set does not support any structural safety conclusion.\n'},
  'image-sorter':{
    'image-manifest.csv':'file,synthetic_label\nbridge.svg,bridge-like drawing\nroad.svg,road-like drawing\nwall.svg,wall-like drawing\n',
    'bridge.svg':svg('Synthetic bridge drawing','#93b8dd','<rect x="90" y="220" width="460" height="28" fill="#445e83"/><path d="M120 220 Q320 40 520 220" fill="none" stroke="#f8fbff" stroke-width="15"/>'),
    'road.svg':svg('Synthetic road drawing','#aacfac','<path d="M245 85 L395 85 L530 345 L110 345 Z" fill="#455b70"/><path d="M320 105 L320 325" stroke="#fff" stroke-width="9" stroke-dasharray="25 22"/>'),
    'wall.svg':svg('Synthetic wall drawing','#d7b292','<g stroke="#9c735e" stroke-width="5"><path d="M65 160h510M65 240h510M65 320h510M190 85v75M430 85v75M310 160v80M170 240v80M440 240v80"/></g>'),
    'test-tags.txt':'Use descriptive labels only. Compare manual tags to the supplied synthetic labels; do not infer real infrastructure condition.\n'
  },
  'community-pulse':{'sample-feedback.csv':'id,feedback\n1,The sample lab schedule is hard to find\n2,I would like a short beginner project guide\n3,Please make sample room signs clearer\n4,A small project checklist would help\n5,The sample lab timetable looks confusing\n','theme-list.txt':'Try schedule, guidance and wayfinding as provisional themes. Show supporting source sentences and an unmatched group.\n'},
  'energy-dashboard':{'sample-energy.csv':'hour,kwh\n08:00,1.2\n09:00,1.5\n10:00,1.7\n11:00,2.1\n12:00,1.9\n13:00,1.6\n14:00,2.4\n15:00,1.8\n','units-guide.txt':'This is a fictional hourly kWh series for a charting exercise. Define any peak rule explicitly. Do not imply real savings or electrical-system performance.\n'},
  'study-plan':{'sample-topics.csv':'topic,priority,minutes\nData cleaning,high,30\nSimple chart,high,35\nModel limitation,high,20\nREADME draft,medium,25\nDemo walkthrough,medium,25\nReview questions,medium,20\n','one-week-outline.txt':'Draft one manageable activity per day, leave time to revisit unclear topics, and let the learner edit the sequence.\n'}
};
