'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { api } from '@/lib/client';

type Channel={source:string;visitors:number;form_starts:number;eligible:number;synthetic_eligible:number};
type Experiment={experiment_id:string;arm:'A'|'B';exposed:number;eligible:number};
type LinkRecord={id:string;source:string;medium:string;partner_id:string;campus_id:string;creative_variant:string;synthetic:boolean};
type Dashboard={workspaceId:string;seeded:boolean;expiresAt:string;targetYear:number;totals:{registrations:number;eligible:number;other_year:number;visitors:number};channel:Channel[];lastTouch:{source:string;eligible:number}[];referral:{issued:number;opens:number;valid:number;primary:number;assists:number};experiments:Experiment[];links:LinkRecord[];events:{type:string;at:string;synthetic:boolean}[]};
const SOURCES=['club','academic','creator','calendar','referral'];
const MEDIA=['group','email','classroom','social','newsletter','direct'];
const TESTS=[
  {id:'preview',title:'Personalised project preview',hypothesis:'A project matched to branch, level and interests raises sign-up intent.',test:'Generic workshop summary (A) versus Matchmaker preview (B).',metric:'Eligible registrations ÷ unique exposed visitors in each arm.'},
  {id:'takehome',title:'Concrete take-home value',hypothesis:'A deliverable starter path raises perceived value.',test:'Broad project description (A) versus actual starter outline, README and next steps (B).',metric:'Eligible registrations ÷ unique exposed visitors in each arm.'},
  {id:'friend',title:'Cross-department friend invite',hypothesis:'Distinct project roles drive more valid peer registrations.',test:'Simple optional invite (A) versus two-branch shared project preview (B).',metric:'New eligible referred registrations ÷ original registrants offered each arm.'},
];
const ratio=(n:number,d:number)=>d?`${(100*n/d).toFixed(1)}%`:'—';
function pack(source:string,medium:string,url:string) {
  const audience=source==='academic'?'final-year engineering students in your department':source==='creator'?'final-year engineering followers':'final-year engineering members';
  return {
    group:`For ${audience}: a free online workshop is proposed, “Build Your First AI Project in 60 Minutes.” Before the event, try a small project starter matched to your engineering branch and interests. The activity is a preview, not a confirmed workshop syllabus. Date, time and instructor are still to be confirmed. Explore the demo and fictional registration here: ${url}`,
    email:`Subject: Proposed free online AI project workshop for final-year engineering students\n\nHello,\n\nWe are preparing a proposed free online session titled “Build Your First AI Project in 60 Minutes” for final-year engineering students. The aim is to help students see a manageable first project path: a small supplied input, a visible first output, and sensible next steps. The independent Campus Relay assessment demo lets a student choose their branch, level and interests, view a curated project preview, and try a fictional registration. The preview is an example of how the offer could be explained; the actual workshop syllabus is not confirmed.\n\nDate, time, instructor, access details and exact curriculum require organiser confirmation before any real announcement. Please review the wording and audience fit before sharing through your ${medium} channel. No student data is collected by this draft and the demo only accepts fictional example.com addresses.\n\nPreview link: ${url}\n\nThank you.`,
    video:`Screen recording script (20 seconds): “Final-year engineering student? Here is a proposed free online workshop: Build Your First AI Project in 60 Minutes. Choose your branch and interests. See a small project starter with a first-hour plan. The workshop details still need confirmation. Explore the independent assessment demo at the link.” Caption: ${url}`,
  };
}

export default function Desk() {
  const {id:workspaceId}=useParams<{id:string}>();
  const [operatorToken,setOperatorToken]=useState(''),[data,setData]=useState<Dashboard|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [source,setSource]=useState('club'),[medium,setMedium]=useState('group'),[partner,setPartner]=useState(''),[campus,setCampus]=useState(''),[variant,setVariant]=useState('standard'),[createdUrl,setCreatedUrl]=useState('');
  const [clubN,setClubN]=useState(20),[clubYield,setClubYield]=useState(15),[academicN,setAcademicN]=useState(8),[academicYield,setAcademicYield]=useState(20),[creatorN,setCreatorN]=useState(10),[creatorYield,setCreatorYield]=useState(10),[invites,setInvites]=useState(100),[inviteRate,setInviteRate]=useState(50),[overlap,setOverlap]=useState(18);
  const [spendCreator,setSpendCreator]=useState(800),[spendAssets,setSpendAssets]=useState(400),[spendHosting,setSpendHosting]=useState(0),[spendReserve,setSpendReserve]=useState(800);
  const [manual,setManual]=useState<Record<string,{aEx:number;aReg:number;bEx:number;bReg:number}>>({});
  useEffect(()=>{const timer=window.setTimeout(()=>{const fragment=new URLSearchParams(window.location.hash.slice(1));const supplied=fragment.get('operator')||localStorage.getItem(`campus-relay-operator-${workspaceId}`)||'';if(supplied){localStorage.setItem(`campus-relay-operator-${workspaceId}`,supplied);setOperatorToken(supplied);history.replaceState(null,'',window.location.pathname);api<Dashboard>(`dashboard?workspaceId=${workspaceId}`,{operatorToken:supplied}).then(setData).catch(e=>setError(e instanceof Error?e.message:'Could not load dashboard.'))}else setError('Open this page with the private Growth desk link created for your workspace.');},0);return()=>window.clearTimeout(timer)},[workspaceId]);
  async function load(key=operatorToken){try{setData(await api<Dashboard>(`dashboard?workspaceId=${workspaceId}`,{operatorToken:key}));setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load dashboard.')}}
  async function createLink(){setBusy(true);setError('');try{const v=await api<{shareUrl:string}>('links',{method:'POST',operatorToken,body:{workspaceId,source,medium,partnerId:partner,campusId:campus,creativeVariant:variant}});setCreatedUrl(v.shareUrl);await load()}catch(e){setError(e instanceof Error?e.message:'Could not issue link.')}finally{setBusy(false)}}
  async function reset(seedMode:boolean){if(!window.confirm(seedMode?'Replace this workspace with synthetic sample records?':'Clear all records in this workspace?'))return;setBusy(true);try{await api(`demo-workspaces/${workspaceId}/reset`,{method:'POST',operatorToken,body:{seedMode}});setCreatedUrl('');await load()}catch(e){setError(e instanceof Error?e.message:'Could not reset.')}finally{setBusy(false)}}
  async function downloadCsv(){try{const r=await fetch(`/api/export.csv?workspaceId=${workspaceId}`,{headers:{'x-operator-token':operatorToken}});if(!r.ok)throw new Error('CSV export failed');const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download='campus-relay-demo.csv';a.click();URL.revokeObjectURL(u)}catch(e){setError(e instanceof Error?e.message:'CSV export failed')}}
  const gross=clubN*clubYield+academicN*academicYield+creatorN*creatorYield+Math.round(invites*inviteRate/100);
  const net=Math.round(gross*(1-overlap/100));
  const lower=Math.round(gross*0.6*(1-overlap/100));
  const totalBudget=spendCreator+spendAssets+spendHosting+spendReserve;
  const forecastValid=[clubN,clubYield,academicN,academicYield,creatorN,creatorYield,invites,spendCreator,spendAssets,spendHosting,spendReserve].every(n=>Number.isFinite(n)&&n>=0)&&[inviteRate,overlap].every(n=>Number.isFinite(n)&&n>=0&&n<=100)&&totalBudget<=2000;
  const prepared=useMemo(()=>pack(source,medium,createdUrl||'(generate a tagged link first)'),[source,medium,createdUrl]);
  const totalEligible=data?.totals.eligible||0;
  return <main className="app-shell desk-shell"><header className="site-header"><Link href="/" className="brand">Campus <span>Relay</span></Link><nav><Link href={`/w/${workspaceId}`}>Student view →</Link></nav></header>
    <div className="desk-heading"><div><h1>Growth desk</h1><p className="disclosure">SIMULATED DATA / NO CAMPAIGN EXECUTED</p><p className="muted">Workspace expires {data?new Date(data.expiresAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'after seven days'}. All records here are fictional; seed rows are synthetic examples.</p></div><div className="desk-actions"><button className="secondary" onClick={()=>load()} disabled={!operatorToken}>Refresh</button><button className="secondary" onClick={downloadCsv} disabled={!data}>Export anonymised CSV</button></div></div>
    {error&&<p className="error" role="alert">{error}</p>}
    {data&&<><div className="metrics"><div><span>Unique eligible registrations</span><strong>{totalEligible}</strong><small>{totalEligible} / 500 target · {data.seeded?'seed + demo':'demo only'}</small></div><div><span>Unique demo visitors</span><strong>{data.totals.visitors}</strong><small>Workspace scope · browser profiles</small></div><div><span>Visit-to-registration rate</span><strong>{ratio(totalEligible,data.totals.visitors)}</strong><small>{totalEligible} / {data.totals.visitors} unique visitors</small></div><div><span>Issued invites</span><strong>{data.referral.issued}</strong><small>{data.referral.opens} opens · {data.referral.valid} eligible friends</small></div></div>
      <div className="desk-two"><section><h2>Channel performance</h2><p className="muted">First-touch source. Eligible registrations count once, so source totals sum to {totalEligible}.</p><div className="table-wrap"><table><thead><tr><th>Source</th><th>Visitors</th><th>Form starts</th><th>Eligible</th><th>Synthetic</th><th>Conversion</th><th>Share</th></tr></thead><tbody>{data.channel.map(c=><tr key={c.source}><td>{c.source.replace('_',' / ')}</td><td>{c.visitors}</td><td>{c.form_starts}</td><td>{c.eligible}</td><td>{c.synthetic_eligible}</td><td>{ratio(c.eligible,c.visitors)}</td><td>{ratio(c.eligible,totalEligible)}</td></tr>)}<tr className="total"><td>Total</td><td>{data.totals.visitors}</td><td>{data.channel.reduce((a,c)=>a+c.form_starts,0)}</td><td>{totalEligible}</td><td>{data.channel.reduce((a,c)=>a+c.synthetic_eligible,0)}</td><td>{ratio(totalEligible,data.totals.visitors)}</td><td>{totalEligible?'100%':'—'}</td></tr></tbody></table></div><p className="fine">Last touch (secondary): {data.lastTouch.map(x=>`${x.source}: ${x.eligible}`).join(' · ')||'none'}. Referral credit: {data.referral.primary} primary, {data.referral.assists} assists. Gross demo receipts: {data.totals.registrations}; other years: {data.totals.other_year}. Registration is not attendance.</p></section>
      <section className="forecast-panel"><h2>Target and forecast</h2><p className="muted">Editable planning assumptions, separate from simulated records. Partner access and yields are unverified.</p><div className="forecast-grid"><label>Clubs <input type="number" min="0" value={clubN} onChange={e=>setClubN(Number(e.target.value))}/></label><label>Per club <input type="number" min="0" value={clubYield} onChange={e=>setClubYield(Number(e.target.value))}/></label><label>Academic shares <input type="number" min="0" value={academicN} onChange={e=>setAcademicN(Number(e.target.value))}/></label><label>Per share <input type="number" min="0" value={academicYield} onChange={e=>setAcademicYield(Number(e.target.value))}/></label><label>Creators <input type="number" min="0" value={creatorN} onChange={e=>setCreatorN(Number(e.target.value))}/></label><label>Per creator <input type="number" min="0" value={creatorYield} onChange={e=>setCreatorYield(Number(e.target.value))}/></label><label>Invites <input type="number" min="0" value={invites} onChange={e=>setInvites(Number(e.target.value))}/></label><label>Friend rate % <input type="number" min="0" max="100" value={inviteRate} onChange={e=>setInviteRate(Number(e.target.value))}/></label><label>Overlap / ineligible % <input type="number" min="0" max="100" value={overlap} onChange={e=>setOverlap(Number(e.target.value))}/></label></div><div className="forecast-result"><span>Gross planned: <strong>{forecastValid?gross:'Check inputs'}</strong></span><span>Estimated unique eligible: <strong>{forecastValid?net:'—'}</strong></span><span>60% yield case: <strong>{forecastValid?lower:'—'}</strong></span></div></section></div>
      <section className="budget"><h2>Proposed budget</h2><p className="muted">₹2,000 ceiling. Actual verified spend: ₹0 in this simulation.</p><div className="budget-fields"><label>Creator production ₹<input type="number" min="0" value={spendCreator} onChange={e=>setSpendCreator(Number(e.target.value))}/></label><label>Visuals and subtitles ₹<input type="number" min="0" value={spendAssets} onChange={e=>setSpendAssets(Number(e.target.value))}/></label><label>Hosting ₹<input type="number" min="0" value={spendHosting} onChange={e=>setSpendHosting(Number(e.target.value))}/></label><label>Reserve ₹<input type="number" min="0" value={spendReserve} onChange={e=>setSpendReserve(Number(e.target.value))}/></label><div className={totalBudget>2000?'error':'budget-total'}>Proposed total ₹{totalBudget} / ₹2,000</div></div>{!forecastValid&&<p className="error" role="alert">Use non-negative counts, percentages from 0 to 100, and a budget no higher than ₹2,000.</p>}</section>
      <section className="experiments"><h2>Three proposed tests</h2><p className="muted">Demo assignments illustrate how exposure denominators work. They are not real campaign tests or evidence of uplift.</p><div className="experiment-list">{TESTS.map(t=>{const a=data.experiments.find(x=>x.experiment_id===t.id&&x.arm==='A'),b=data.experiments.find(x=>x.experiment_id===t.id&&x.arm==='B');const m=manual[t.id]||{aEx:a?.exposed||0,aReg:a?.eligible||0,bEx:b?.exposed||0,bReg:b?.eligible||0};const valid=m.aEx>=0&&m.bEx>=0&&m.aReg>=0&&m.bReg>=0&&m.aReg<=m.aEx&&m.bReg<=m.bEx;return <article key={t.id}><div><h3>{t.title}</h3><p><strong>Hypothesis:</strong> {t.hypothesis}</p><p><strong>Test:</strong> {t.test}</p><p><strong>Metric:</strong> {t.metric}</p></div><div className="experiment-counts"><div><strong>Arm A</strong><label>Exposed<input type="number" min="0" value={m.aEx} onChange={e=>setManual({...manual,[t.id]:{...m,aEx:Number(e.target.value)}})}/></label><label>Eligible<input type="number" min="0" value={m.aReg} onChange={e=>setManual({...manual,[t.id]:{...m,aReg:Number(e.target.value)}})}/></label></div><div><strong>Arm B</strong><label>Exposed<input type="number" min="0" value={m.bEx} onChange={e=>setManual({...manual,[t.id]:{...m,bEx:Number(e.target.value)}})}/></label><label>Eligible<input type="number" min="0" value={m.bReg} onChange={e=>setManual({...manual,[t.id]:{...m,bReg:Number(e.target.value)}})}/></label></div><p className={valid?'fine':'error'}>{valid?`${ratio(m.aReg,m.aEx)} A · ${ratio(m.bReg,m.bEx)} B; directional only`:'Registrations cannot exceed exposures.'}</p></div></article>})}</div></section>
      <section className="links-section"><h2>Tracked partner links and draft pack</h2><p className="muted">Issue a distinct link for a club, academic contact, creator or calendar. Drafts are editable and never sent by this app.</p><div className="link-form"><label>Source<select value={source} onChange={e=>setSource(e.target.value)}>{SOURCES.map(s=><option key={s}>{s}</option>)}</select></label><label>Medium<select value={medium} onChange={e=>setMedium(e.target.value)}>{MEDIA.map(s=><option key={s}>{s}</option>)}</select></label><label>Partner ID<input value={partner} maxLength={60} onChange={e=>setPartner(e.target.value)} placeholder="e.g. coding-club"/></label><label>Campus ID<input value={campus} maxLength={60} onChange={e=>setCampus(e.target.value)} placeholder="optional"/></label><label>Creative variant<input value={variant} maxLength={60} onChange={e=>setVariant(e.target.value)} /></label><button className="primary" onClick={createLink} disabled={busy}>Generate link</button></div>{createdUrl&&<div className="generated-link"><label>Tagged URL<input readOnly value={createdUrl} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={()=>navigator.clipboard.writeText(createdUrl)}>Copy</button></div>}<div className="pack-grid"><label>Group post (draft)<textarea defaultValue={prepared.group} key={`group-${createdUrl}-${source}-${medium}`}/></label><label>Academic email (draft)<textarea defaultValue={prepared.email} key={`email-${createdUrl}-${source}-${medium}`}/></label><label>20-second video script and caption (draft)<textarea defaultValue={prepared.video} key={`video-${createdUrl}-${source}-${medium}`}/></label></div><p className="fine">Example project: {source==='creator'?'sensor reading explorer':'campus FAQ finder'}. FAQ: free, online, 60 minutes proposed; date, instructor and exact syllabus pending organiser confirmation. A partner and organiser must approve a real message before sharing.</p><h3>Issued links</h3><div className="table-wrap"><table><thead><tr><th>Source</th><th>Medium</th><th>Partner</th><th>Campus</th><th>Variant</th><th>Type</th></tr></thead><tbody>{data.links.map(l=><tr key={l.id}><td>{l.source}</td><td>{l.medium}</td><td>{l.partner_id||'—'}</td><td>{l.campus_id||'—'}</td><td>{l.creative_variant}</td><td>{l.synthetic?'Synthetic seed':'Demo issued'}</td></tr>)}</tbody></table></div></section>
      <section className="workspace-tools"><h2>Workspace controls</h2><p>Reset clears registrations, invites, visits and links. Reseed creates visibly synthetic examples.</p><button className="secondary" onClick={()=>reset(false)} disabled={busy}>Reset to empty</button><button className="secondary" onClick={()=>reset(true)} disabled={busy}>Reseed examples</button></section>
    </>}
    <footer className="site-footer">Independent candidate assessment simulation, built with AI assistance. No actual campaign, official syllabus or verified student identity.</footer>
  </main>;
}
